import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="gap-10 flex flex-col">
        <header>
          [Header]
        </header>
        <main>{children}</main>
        <footer>
          [footer]
        </footer>
      </body>
    </html>
  );
}
